
import java.awt.event.ItemEvent;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SearchAndReplace.java
 *
 * Created on 01.04.2011, 16:41:53
 */
/**
 *
 * @author kraemer
 */
public class SearchAndReplace extends javax.swing.JDialog {

	Editor editor;

	/** Creates new form SearchAndReplace */
	public SearchAndReplace(java.awt.Frame parent, boolean modal, Editor editor) {
		super(parent, modal);
		this.editor = editor;
		initComponents();
		/*this.addWindowListener(new java.awt.event.WindowAdapter() {

		@Override
		public void windowClosing(java.awt.event.WindowEvent e) {
		//				.setVisible(false);
		}
		});*/
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {
    java.awt.GridBagConstraints gridBagConstraints;

    buttonSearch = new javax.swing.JButton();
    buttonReplace = new javax.swing.JButton();
    buttonReplaceAll = new javax.swing.JButton();
    buttonClose = new javax.swing.JButton();
    checkCase = new javax.swing.JCheckBox();
    checkWholeWords = new javax.swing.JCheckBox();
    checkRegEx = new javax.swing.JCheckBox();
    jLabel1 = new javax.swing.JLabel();
    jLabel2 = new javax.swing.JLabel();
    searchText = new javax.swing.JComboBox();
    replaceText = new javax.swing.JComboBox();

    getContentPane().setLayout(new java.awt.GridBagLayout());

    buttonSearch.setText("Suchen");
    buttonSearch.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        buttonSearchActionPerformed(evt);
      }
    });
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 2;
    gridBagConstraints.gridy = 0;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.insets = new java.awt.Insets(2, 15, 2, 5);
    getContentPane().add(buttonSearch, gridBagConstraints);

    buttonReplace.setText("Ersetzen");
    buttonReplace.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        buttonReplaceActionPerformed(evt);
      }
    });
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 2;
    gridBagConstraints.gridy = 1;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.insets = new java.awt.Insets(2, 15, 2, 5);
    getContentPane().add(buttonReplace, gridBagConstraints);

    buttonReplaceAll.setText("Alle Ersetzen");
    buttonReplaceAll.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        buttonReplaceAllActionPerformed(evt);
      }
    });
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 2;
    gridBagConstraints.gridy = 2;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
    gridBagConstraints.insets = new java.awt.Insets(2, 15, 2, 5);
    getContentPane().add(buttonReplaceAll, gridBagConstraints);

    buttonClose.setText("Schließen");
    buttonClose.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        buttonCloseActionPerformed(evt);
      }
    });
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 2;
    gridBagConstraints.gridy = 4;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.insets = new java.awt.Insets(2, 15, 2, 5);
    getContentPane().add(buttonClose, gridBagConstraints);

    checkCase.setText("Groß-/Kleinschreibung beachten");
    checkCase.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        checkCaseActionPerformed(evt);
      }
    });
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 2;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
    gridBagConstraints.insets = new java.awt.Insets(15, 0, 0, 0);
    getContentPane().add(checkCase, gridBagConstraints);

    checkWholeWords.setText("ganze Wörter");
    checkWholeWords.setEnabled(false);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 3;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
    getContentPane().add(checkWholeWords, gridBagConstraints);

    checkRegEx.setText("reguläre Ausdrücke");
    checkRegEx.setEnabled(false);
    checkRegEx.addItemListener(new java.awt.event.ItemListener() {
      public void itemStateChanged(java.awt.event.ItemEvent evt) {
        checkRegExItemStateChanged(evt);
      }
    });
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 4;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
    getContentPane().add(checkRegEx, gridBagConstraints);

    jLabel1.setText("Suchen");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 0;
    gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 5);
    getContentPane().add(jLabel1, gridBagConstraints);

    jLabel2.setText("Ersetzen");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 1;
    gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 5);
    getContentPane().add(jLabel2, gridBagConstraints);

    searchText.setEditable(true);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 0;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.weightx = 1.0;
    getContentPane().add(searchText, gridBagConstraints);

    replaceText.setEditable(true);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 1;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.weightx = 1.0;
    getContentPane().add(replaceText, gridBagConstraints);

    pack();
  }// </editor-fold>//GEN-END:initComponents

		private void checkCaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkCaseActionPerformed
			// TODO add your handling code here:
		}//GEN-LAST:event_checkCaseActionPerformed

		private void buttonReplaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonReplaceActionPerformed
			if(searchText.getSelectedIndex()==-1 && searchText.getSelectedItem()!=null){
				searchText.addItem(searchText.getSelectedItem());
			}
			if(replaceText.getSelectedIndex()==-1 && replaceText.getSelectedItem()!=null){
				replaceText.addItem(replaceText.getSelectedItem());
			}

			editor.replace((String)searchText.getSelectedItem(),(String)replaceText.getSelectedItem(),checkCase.isSelected(),checkWholeWords.isSelected());//searchText.toString());
		}//GEN-LAST:event_buttonReplaceActionPerformed

		private void buttonCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCloseActionPerformed
			this.setVisible(false);
		}//GEN-LAST:event_buttonCloseActionPerformed

		private void buttonSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSearchActionPerformed
			if(searchText.getSelectedIndex()==-1 && searchText.getSelectedItem()!=null){
				searchText.addItem(searchText.getSelectedItem());
			}
			editor.search((String)searchText.getSelectedItem(),checkCase.isSelected(),checkWholeWords.isSelected());//searchText.toString());

		}//GEN-LAST:event_buttonSearchActionPerformed

		private void checkRegExItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_checkRegExItemStateChanged
			// TODO add your handling code here:
			if(evt.getStateChange()==ItemEvent.SELECTED){
				this.checkCase.setEnabled(false);
				this.checkWholeWords.setEnabled(false);
			}else{
				this.checkCase.setEnabled(true);
				this.checkWholeWords.setEnabled(true);
			}
		}//GEN-LAST:event_checkRegExItemStateChanged

		private void buttonReplaceAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonReplaceAllActionPerformed
			if(searchText.getSelectedIndex()==-1 && searchText.getSelectedItem()!=null){
				searchText.addItem(searchText.getSelectedItem());
			}
			if(replaceText.getSelectedIndex()==-1 && replaceText.getSelectedItem()!=null){
				replaceText.addItem(replaceText.getSelectedItem());
			}

			editor.replaceAll((String)searchText.getSelectedItem(),(String)replaceText.getSelectedItem(),checkCase.isSelected(),checkWholeWords.isSelected());//searchText.toString());
		}//GEN-LAST:event_buttonReplaceAllActionPerformed

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton buttonClose;
  private javax.swing.JButton buttonReplace;
  private javax.swing.JButton buttonReplaceAll;
  private javax.swing.JButton buttonSearch;
  private javax.swing.JCheckBox checkCase;
  private javax.swing.JCheckBox checkRegEx;
  private javax.swing.JCheckBox checkWholeWords;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JComboBox replaceText;
  private javax.swing.JComboBox searchText;
  // End of variables declaration//GEN-END:variables
}
