<?php
/**
 * webEdition CMS
 *
 * $Rev$
 * $Author$
 * $Date$
 *
 * This source is part of webEdition CMS. webEdition CMS is
 * free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * any later version.
 *
 * The GNU General Public License can be found at
 * http://www.gnu.org/copyleft/gpl.html.
 * A copy is found in the textfile
 * webEdition/licenses/webEditionCMS/License.txt
 *
 * @category   webEdition
 * @package none
 * @license    http://www.gnu.org/copyleft/gpl.html  GPL
 */
return ['html' => array(
		'a' => array(
			'default' => array('class', 'accesskey', 'tabindex', 'id', 'style', 'title', 'dir', 'lang'),
			'js' => array('onclick', 'ondblclick', 'onmousedown', 'onmouseup', 'onmouseover', 'onmousemove', 'onmouseout', 'onkeypress', 'onkeydown', 'onkeyup', 'onblur', 'onfocus',),
			'norm' => array('accesskey', 'charset', 'coords', 'href', 'hreflang', 'name', 'rel', 'rev', 'shape', 'tabindex', 'target', 'type'),
			'default_html5' => array('contenteditable', 'contextmenu', 'draggable', 'dropzone', 'hidden', 'spellcheck'),
			'html5' => [],
		),
		'abbr' => array(
			'default' => array('class', 'accesskey', 'tabindex', 'id', 'style', 'title', 'dir', 'lang'),
			'js' => array('onclick', 'ondblclick', 'onmousedown', 'onmouseup', 'onmouseover', 'onmousemove', 'onmouseout', 'onkeypress', 'onkeydown', 'onkeyup'),
			'norm' => [],
			'default_html5' => array('contenteditable', 'contextmenu', 'draggable', 'dropzone', 'hidden', 'spellcheck'),
			'html5' => [],
		),
		'acronym' => array(
			'default' => array('class', 'accesskey', 'tabindex', 'id', 'style', 'title', 'dir', 'lang'),
			'js' => array('onclick', 'ondblclick', 'onmousedown', 'onmouseup', 'onmouseover', 'onmousemove', 'onmouseout', 'onkeypress', 'onkeydown', 'onkeyup'),
			'norm' => [],
			'default_html5' => array('contenteditable', 'contextmenu', 'draggable', 'dropzone', 'hidden', 'spellcheck'),
			'html5' => [],
		),
		'address' => array(
			'default' => array('class', 'accesskey', 'tabindex', 'id', 'style', 'title', 'dir', 'lang'),
			'js' => array('onclick', 'ondblclick', 'onmousedown', 'onmouseup', 'onmouseover', 'onmousemove', 'onmouseout', 'onkeypress', 'onkeydown', 'onkeyup'),
			'norm' => array('contenteditable', 'contextmenu', 'dir', 'draggable', 'irrelevant', 'ref', 'tabindex'),
			'default_html5' => array('contenteditable', 'contextmenu', 'draggable', 'dropzone', 'hidden', 'spellcheck'),
			'html5' => [],
		),
		'applet' => array(
			'default' => array('class', 'accesskey', 'tabindex', 'id', 'style', 'title'),
			'js' => array('onload'),
			'norm' => array('align', 'alt', 'archive', 'code', 'codebase', 'height', 'hspace', 'name', 'object', 'vspace', 'width'),
			'default_html5' => array('contenteditable', 'contextmenu', 'draggable', 'dropzone', 'hidden', 'spellcheck'),
			'html5' => [],
		),
		'area' => array(
			'default' => array('id', 'title'),
			'js' => array('onclick', 'ondblclick', 'onmousedown', 'onmouseup', 'onmouseover', 'onmousemove', 'onmouseout', 'onkeypress', 'onkeydown', 'onkeyup', 'onblur', 'onfocus'),
			'norm' => array('accesskey', 'alt', 'coords', 'href', 'nohref', 'shape', 'tabindex', 'target'),
			'default_html5' => array('contenteditable', 'contextmenu', 'draggable', 'dropzone', 'hidden', 'spellcheck'),
			'html5' => [],
		),
		'b' => array(
			'default' => array('class', 'accesskey', 'tabindex', 'id', 'style', 'title', 'dir', 'lang'),
			'js' => array('onclick', 'ondblclick', 'onmousedown', 'onmouseup', 'onmouseover', 'onmousemove', 'onmouseout', 'onkeypress', 'onkeydown', 'onkeyup'),
			'norm' => [],
			'default_html5' => array('contenteditable', 'contextmenu', 'draggable', 'dropzone', 'hidden', 'spellcheck'),
			'html5' => [],
		),
		'base' => array(
			'default' => [],
			'js' => [],
			'norm' => array('href', 'target'),
			'default_html5' => array('contenteditable', 'contextmenu', 'draggable', 'dropzone', 'hidden', 'spellcheck'),
			'html5' => [],
		),
		'basefont' => array(
			'default' => array('id'),
			'js' => [],
			'norm' => array('color', 'face', 'size'),
			'default_html5' => array('contenteditable', 'contextmenu', 'draggable', 'dropzone', 'hidden', 'spellcheck'),
			'html5' => [],
		),
		'bdo' => array(
			'default' => array('class', 'accesskey', 'tabindex', 'id', 'style', 'title', 'dir'),
			'js' => [],
			'norm' => [],
			'default_html5' => array('contenteditable', 'contextmenu', 'draggable', 'dropzone', 'hidden', 'spellcheck'),
			'html5' => [],
		),
		'big' => array(
			'default' => array('class', 'accesskey', 'tabindex', 'id', 'style', 'title', 'dir', 'lang'),
			'js' => array('onclick', 'ondblclick', 'onmousedown', 'onmouseup', 'onmouseover', 'onmousemove', 'onmouseout', 'onkeypress', 'onkeydown', 'onkeyup'),
			'norm' => [],
			'default_html5' => array('contenteditable', 'contextmenu', 'draggable', 'dropzone', 'hidden', 'spellcheck'),
			'html5' => [],
		),
		'blockquote' => array(
			'default' => array('class', 'accesskey', 'tabindex', 'id', 'style', 'title', 'dir', 'lang'),
			'js' => array('onclick', 'ondblclick', 'onmousedown', 'onmouseup', 'onmouseover', 'onmousemove', 'onmouseout', 'onkeypress', 'onkeydown', 'onkeyup'),
			'norm' => array('cite'),
			'default_html5' => array('contenteditable', 'contextmenu', 'draggable', 'dropzone', 'hidden', 'spellcheck'),
			'html5' => [],
		),
		'body' => array(
			'default' => array('class', 'accesskey', 'tabindex', 'id', 'style', 'title', 'dir', 'lang'),
			'js' => array('onclick', 'ondblclick', 'onmousedown', 'onmouseup', 'onmouseover', 'onmousemove', 'onmouseout', 'onkeypress', 'onkeydown', 'onkeyup', 'onload', 'onunload'),
			'norm' => array('alink', 'background', 'bgcolor', 'link', 'text', 'vlink'),
			'default_html5' => array('contenteditable', 'contextmenu', 'draggable', 'dropzone', 'hidden', 'spellcheck'),
			'html5' => [],
		),
		'br' => array(
			'default' => array('class', 'accesskey', 'tabindex', 'id', 'style', 'title',),
			'js' => [],
			'norm' => array('clear'),
			'default_html5' => array('contenteditable', 'contextmenu', 'draggable', 'dropzone', 'hidden', 'spellcheck'),
			'html5' => [],
		),
		'button' => array(
			'default' => array('class', 'accesskey', 'tabindex', 'id', 'style', 'title', 'dir', 'lang'),
			'js' => array('onclick', 'ondblclick', 'onmousedown', 'onmouseup', 'onmouseover', 'onmousemove', 'onmouseout', 'onkeypress', 'onkeydown', 'onkeyup', 'onblur', 'onfocus'),
			'norm' => array('accesskey', 'disabled="disabled"', 'name', 'tabindex', 'type', 'value'),
			'default_html5' => array('contenteditable', 'contextmenu', 'draggable', 'dropzone', 'hidden', 'spellcheck'),
			'html5' => [],
		),
		'caption' => array(
			'default' => array('class', 'accesskey', 'tabindex', 'id', 'style', 'title', 'dir', 'lang'),
			'js' => array('onclick', 'ondblclick', 'onmousedown', 'onmouseup', 'onmouseover', 'onmousemove', 'onmouseout', 'onkeypress', 'onkeydown', 'onkeyup'),
			'norm' => array('align'),
			'default_html5' => array('contenteditable', 'contextmenu', 'draggable', 'dropzone', 'hidden', 'spellcheck'),
			'html5' => [],
		),
		'center' => array(
			'default' => array('class', 'accesskey', 'tabindex', 'id', 'style', 'title', 'dir', 'lang'),
			'js' => array('onclick', 'ondblclick', 'onmousedown', 'onmouseup', 'onmouseover', 'onmousemove', 'onmouseout', 'onkeypress', 'onkeydown', 'onkeyup'),
			'norm' => [],
			'default_html5' => array('contenteditable', 'contextmenu', 'draggable', 'dropzone', 'hidden', 'spellcheck'),
			'html5' => [],
		),
		'cite' => array(
			'default' => array('class', 'accesskey', 'tabindex', 'id', 'style', 'title', 'dir', 'lang'),
			'js' => array('onclick', 'ondblclick', 'onmousedown', 'onmouseup', 'onmouseover', 'onmousemove', 'onmouseout', 'onkeypress', 'onkeydown', 'onkeyup'),
			'norm' => [],
			'default_html5' => array('contenteditable', 'contextmenu', 'draggable', 'dropzone', 'hidden', 'spellcheck'),
			'html5' => [],
		),
		'code' => array(
			'default' => array('class', 'accesskey', 'tabindex', 'id', 'style', 'title', 'dir', 'lang'),
			'js' => array('onclick', 'ondblclick', 'onmousedown', 'onmouseup', 'onmouseover', 'onmousemove', 'onmouseout', 'onkeypress', 'onkeydown', 'onkeyup'),
			'norm' => [],
			'default_html5' => array('contenteditable', 'contextmenu', 'draggable', 'dropzone', 'hidden', 'spellcheck'),
			'html5' => [],
		),
		'col' => array(
			'default' => array('class', 'accesskey', 'tabindex', 'id', 'style', 'title', 'dir', 'lang'),
			'js' => array('onclick', 'ondblclick', 'onmousedown', 'onmouseup', 'onmouseover', 'onmousemove', 'onmouseout', 'onkeypress', 'onkeydown', 'onkeyup'),
			'norm' => array('align', 'char', 'charoff', 'span', 'valign', 'width'),
			'default_html5' => array('contenteditable', 'contextmenu', 'draggable', 'dropzone', 'hidden', 'spellcheck'),
			'html5' => [],
		),
		'colgroup' => array(
			'default' => array('class', 'accesskey', 'tabindex', 'id', 'style', 'title', 'dir', 'lang'),
			'js' => array('onclick', 'ondblclick', 'onmousedown', 'onmouseup', 'onmouseover', 'onmousemove', 'onmouseout', 'onkeypress', 'onkeydown', 'onkeyup'),
			'norm' => array('align', 'char', 'charoff', 'span', 'valign', 'width'),
			'default_html5' => array('contenteditable', 'contextmenu', 'draggable', 'dropzone', 'hidden', 'spellcheck'),
			'html5' => [],
		),
		'dd' => array(
			'default' => array('class', 'accesskey', 'tabindex', 'id', 'style', 'title', 'dir', 'lang'),
			'js' => array('onclick', 'ondblclick', 'onmousedown', 'onmouseup', 'onmouseover', 'onmousemove', 'onmouseout', 'onkeypress', 'onkeydown', 'onkeyup'),
			'norm' => [],
			'default_html5' => array('contenteditable', 'contextmenu', 'draggable', 'dropzone', 'hidden', 'spellcheck'),
			'html5' => [],
		),
		'del' => array(
			'default' => array('class', 'accesskey', 'tabindex', 'id', 'style', 'title', 'dir', 'lang'),
			'js' => array('onclick', 'ondblclick', 'onmousedown', 'onmouseup', 'onmouseover', 'onmousemove', 'onmouseout', 'onkeypress', 'onkeydown', 'onkeyup'),
			'norm' => array('cite', 'datetime'),
			'default_html5' => array('contenteditable', 'contextmenu', 'draggable', 'dropzone', 'hidden', 'spellcheck'),
			'html5' => [],
		),
		'dfn' => array(
			'default' => array('class', 'accesskey', 'tabindex', 'id', 'style', 'title', 'dir', 'lang'),
			'js' => array('onclick', 'ondblclick', 'onmousedown', 'onmouseup', 'onmouseover', 'onmousemove', 'onmouseout', 'onkeypress', 'onkeydown', 'onkeyup'),
			'norm' => [],
			'default_html5' => array('contenteditable', 'contextmenu', 'draggable', 'dropzone', 'hidden', 'spellcheck'),
			'html5' => [],
		),
		'dir' => array(
			'default' => array('class', 'accesskey', 'tabindex', 'id', 'style', 'title', 'dir', 'lang'),
			'js' => array('onclick', 'ondblclick', 'onmousedown', 'onmouseup', 'onmouseover', 'onmousemove', 'onmouseout', 'onkeypress', 'onkeydown', 'onkeyup'),
			'norm' => array('compact'),
			'default_html5' => array('contenteditable', 'contextmenu', 'draggable', 'dropzone', 'hidden', 'spellcheck'),
			'html5' => [],
		),
		'div' => array(
			'default' => array('class', 'accesskey', 'tabindex', 'id', 'style', 'title', 'dir', 'lang'),
			'js' => array('onclick', 'ondblclick', 'onmousedown', 'onmouseup', 'onmouseover', 'onmousemove', 'onmouseout', 'onkeypress', 'onkeydown', 'onkeyup'),
			'norm' => array('align'),
			'default_html5' => array('contenteditable', 'contextmenu', 'draggable', 'dropzone', 'hidden', 'spellcheck'),
			'html5' => [],
		),
		'dl' => array(
			'default' => array('class', 'accesskey', 'tabindex', 'id', 'style', 'title', 'dir', 'lang'),
			'js' => array('onclick', 'ondblclick', 'onmousedown', 'onmouseup', 'onmouseover', 'onmousemove', 'onmouseout', 'onkeypress', 'onkeydown', 'onkeyup'),
			'norm' => array('compact'),
			'default_html5' => array('contenteditable', 'contextmenu', 'draggable', 'dropzone', 'hidden', 'spellcheck'),
			'html5' => [],
		),
		'dt' => array(
			'default' => array('class', 'accesskey', 'tabindex', 'id', 'style', 'title', 'dir', 'lang'),
			'js' => array('onclick', 'ondblclick', 'onmousedown', 'onmouseup', 'onmouseover', 'onmousemove', 'onmouseout', 'onkeypress', 'onkeydown', 'onkeyup'),
			'norm' => [],
			'default_html5' => array('contenteditable', 'contextmenu', 'draggable', 'dropzone', 'hidden', 'spellcheck'),
			'html5' => [],
		),
		'em' => array(
			'default' => array('class', 'accesskey', 'tabindex', 'id', 'style', 'title', 'dir', 'lang'),
			'js' => array('onclick', 'ondblclick', 'onmousedown', 'onmouseup', 'onmouseover', 'onmousemove', 'onmouseout', 'onkeypress', 'onkeydown', 'onkeyup'),
			'norm' => [],
			'default_html5' => array('contenteditable', 'contextmenu', 'draggable', 'dropzone', 'hidden', 'spellcheck'),
			'html5' => [],
		),
		'fieldset' => array(
			'default' => array('class', 'accesskey', 'tabindex', 'id', 'style', 'title', 'dir', 'lang'),
			'js' => array('onclick', 'ondblclick', 'onmousedown', 'onmouseup', 'onmouseover', 'onmousemove', 'onmouseout', 'onkeypress', 'onkeydown', 'onkeyup'),
			'norm' => [],
			'default_html5' => array('contenteditable', 'contextmenu', 'draggable', 'dropzone', 'hidden', 'spellcheck'),
			'html5' => [],
		),
		'font' => array(
			'default' => array('class', 'accesskey', 'tabindex', 'id', 'style', 'title', 'dir', 'lang'),
			'js' => [],
			'norm' => array('color', 'face', 'size'),
			'default_html5' => array('contenteditable', 'contextmenu', 'draggable', 'dropzone', 'hidden', 'spellcheck'),
			'html5' => [],
		),
		'form' => array(
			'default' => array('class', 'accesskey', 'tabindex', 'id', 'style', 'title', 'dir', 'lang'),
			'js' => array('onclick', 'ondblclick', 'onmousedown', 'onmouseup', 'onmouseover', 'onmousemove', 'onmouseout', 'onkeypress', 'onkeydown', 'onkeyup', 'onreset', 'onsubmit'),
			'norm' => array('action', 'accept', 'accept-charset', 'enctype', 'method', 'name', 'target'),
			'default_html5' => array('contenteditable', 'contextmenu', 'draggable', 'dropzone', 'hidden', 'spellcheck'),
			'html5' => [],
		),
		'frame' => array(
			'default' => array('class', 'accesskey', 'tabindex', 'id', 'style', 'title',),
			'js' => [],
			'norm' => array('frameborder', 'longdesc', 'marginheight', 'marginwidth', 'name', 'noresize', 'scrolling', 'src'),
			'default_html5' => array('contenteditable', 'contextmenu', 'draggable', 'dropzone', 'hidden', 'spellcheck'),
			'html5' => [],
		),
		'frameset' => array(
			'default' => array('class', 'accesskey', 'tabindex', 'id', 'style', 'title', 'dir', 'lang'),
			'js' => array('onload', 'onunload'),
			'norm' => array('cols', 'rows'),
			'default_html5' => array('contenteditable', 'contextmenu', 'draggable', 'dropzone', 'hidden', 'spellcheck'),
			'html5' => [],
		),
		'h1' => array(
			'default' => array('class', 'accesskey', 'tabindex', 'id', 'style', 'title', 'dir', 'lang'),
			'js' => array('onclick', 'ondblclick', 'onmousedown', 'onmouseup', 'onmouseover', 'onmousemove', 'onmouseout', 'onkeypress', 'onkeydown', 'onkeyup'),
			'norm' => array('align'),
			'default_html5' => array('contenteditable', 'contextmenu', 'draggable', 'dropzone', 'hidden', 'spellcheck'),
			'html5' => [],
		),
		'h2' => array(
			'default' => array('class', 'accesskey', 'tabindex', 'id', 'style', 'title', 'dir', 'lang'),
			'js' => array('onclick', 'ondblclick', 'onmousedown', 'onmouseup', 'onmouseover', 'onmousemove', 'onmouseout', 'onkeypress', 'onkeydown', 'onkeyup'),
			'norm' => array('align'),
			'default_html5' => array('contenteditable', 'contextmenu', 'draggable', 'dropzone', 'hidden', 'spellcheck'),
			'html5' => [],
		),
		'h3' => array(
			'default' => array('class', 'accesskey', 'tabindex', 'id', 'style', 'title', 'dir', 'lang'),
			'js' => array('onclick', 'ondblclick', 'onmousedown', 'onmouseup', 'onmouseover', 'onmousemove', 'onmouseout', 'onkeypress', 'onkeydown', 'onkeyup'),
			'norm' => array('align'),
			'default_html5' => array('contenteditable', 'contextmenu', 'draggable', 'dropzone', 'hidden', 'spellcheck'),
			'html5' => [],
		),
		'h4' => array(
			'default' => array('class', 'accesskey', 'tabindex', 'id', 'style', 'title', 'dir', 'lang'),
			'js' => array('onclick', 'ondblclick', 'onmousedown', 'onmouseup', 'onmouseover', 'onmousemove', 'onmouseout', 'onkeypress', 'onkeydown', 'onkeyup'),
			'norm' => array('align'),
			'default_html5' => array('contenteditable', 'contextmenu', 'draggable', 'dropzone', 'hidden', 'spellcheck'),
			'html5' => [],
		),
		'h5' => array(
			'default' => array('class', 'accesskey', 'tabindex', 'id', 'style', 'title', 'dir', 'lang'),
			'js' => array('onclick', 'ondblclick', 'onmousedown', 'onmouseup', 'onmouseover', 'onmousemove', 'onmouseout', 'onkeypress', 'onkeydown', 'onkeyup'),
			'norm' => array('align'),
			'default_html5' => array('contenteditable', 'contextmenu', 'draggable', 'dropzone', 'hidden', 'spellcheck'),
			'html5' => [],
		),
		'h6' => array(
			'default' => array('class', 'accesskey', 'tabindex', 'id', 'style', 'title', 'dir', 'lang'),
			'js' => array('onclick', 'ondblclick', 'onmousedown', 'onmouseup', 'onmouseover', 'onmousemove', 'onmouseout', 'onkeypress', 'onkeydown', 'onkeyup'),
			'norm' => array('align'),
			'default_html5' => array('contenteditable', 'contextmenu', 'draggable', 'dropzone', 'hidden', 'spellcheck'),
			'html5' => [],
		),
		'head' => array(
			'default' => array('dir', 'lang'),
			'js' => [],
			'norm' => array('profile'),
			'default_html5' => array('contenteditable', 'contextmenu', 'draggable', 'dropzone', 'hidden', 'spellcheck'),
			'html5' => [],
		),
		'hr' => array(
			'default' => array('class', 'accesskey', 'tabindex', 'id', 'style', 'title', 'dir', 'lang'),
			'js' => array('onclick', 'ondblclick', 'onmousedown', 'onmouseup', 'onmouseover', 'onmousemove', 'onmouseout', 'onkeypress', 'onkeydown', 'onkeyup'),
			'norm' => array('align', 'noshade', 'size', 'width'),
			'default_html5' => array('contenteditable', 'contextmenu', 'draggable', 'dropzone', 'hidden', 'spellcheck'),
			'html5' => [],
		),
		'html' => array(
			'default' => array('dir', 'lang'),
			'js' => [],
			'norm' => array('version'),
			'default_html5' => array('contenteditable', 'contextmenu', 'draggable', 'dropzone', 'hidden', 'spellcheck'),
			'html5' => [],
		),
		'i' => array(
			'default' => array('class', 'accesskey', 'tabindex', 'id', 'style', 'title', 'dir', 'lang'),
			'js' => array('onclick', 'ondblclick', 'onmousedown', 'onmouseup', 'onmouseover', 'onmousemove', 'onmouseout', 'onkeypress', 'onkeydown', 'onkeyup'),
			'norm' => [],
			'default_html5' => array('contenteditable', 'contextmenu', 'draggable', 'dropzone', 'hidden', 'spellcheck'),
			'html5' => [],
		),
		'iframe' => array(
			'default' => array('class', 'accesskey', 'tabindex', 'id', 'style', 'title'),
			'js' => [],
			'norm' => array('align', 'frameborder', 'height', 'longdesc', 'marginheight', 'marginwidth', 'name', 'scrolling', 'src', 'width'),
			'default_html5' => array('contenteditable', 'contextmenu', 'draggable', 'dropzone', 'hidden', 'spellcheck'),
			'html5' => [],
		),
		'img' => array(
			'default' => array('class', 'accesskey', 'tabindex', 'id', 'style', 'title', 'dir', 'lang'),
			'js' => array('onclick', 'ondblclick', 'onmousedown', 'onmouseup', 'onmouseover', 'onmousemove', 'onmouseout', 'onkeypress', 'onkeydown', 'onkeyup', 'onerror', 'onload'),
			'norm' => array('align', 'alt', 'border', 'height', 'hspace', 'ismap', 'longdesc', 'name', 'src', 'usemap', 'vspace', 'width'),
			'default_html5' => array('contenteditable', 'contextmenu', 'draggable', 'dropzone', 'hidden', 'spellcheck'),
			'html5' => [],
		),
		'input' => array(
			'default' => array('class', 'accesskey', 'tabindex', 'id', 'style', 'title', 'dir', 'lang'),
			'js' => array('onclick', 'ondblclick', 'onmousedown', 'onmouseup', 'onmouseover', 'onmousemove', 'onmouseout', 'onkeypress', 'onkeydown', 'onkeyup', 'onchange', 'onblur', 'onfocus', 'onselect'),
			'norm' => array('accept', 'accesskey', 'align', 'alt', 'checked="checked"', 'disabled="disabled"', 'ismap', 'maxlength', 'name', 'readonly', 'size', 'src', 'tabindex', 'type', 'usemap', 'value', 'type="button"', 'type="hidden"', 'type="file"', 'type="submit"', 'type="checkbox"', 'type="password"', 'type="radio"', 'type="reset"',),
			'default_html5' => array('contenteditable', 'contextmenu', 'draggable', 'dropzone', 'hidden', 'spellcheck'),
			'html5' => array('type = "color"', 'type = "date"', 'type = "datetime"', 'type = "datetime-local"', 'type = "email"', 'type = "image"', 'type = "month"', 'type = "number"', 'type = "range"', 'type = "search"', 'type = "tel"', 'type = "text"', 'type = "time"', 'type = "url"', 'type = "week"'),
		),
		'ins' => array(
			'default' => array('class', 'accesskey', 'tabindex', 'id', 'style', 'title', 'dir', 'lang'),
			'js' => array('onclick', 'ondblclick', 'onmousedown', 'onmouseup', 'onmouseover', 'onmousemove', 'onmouseout', 'onkeypress', 'onkeydown', 'onkeyup'),
			'norm' => array('cite', 'datetime'),
			'default_html5' => array('contenteditable', 'contextmenu', 'draggable', 'dropzone', 'hidden', 'spellcheck'),
			'html5' => [],
		),
		'kbd' => array(
			'default' => array('class', 'accesskey', 'tabindex', 'id', 'style', 'title', 'dir', 'lang'),
			'js' => array('onclick', 'ondblclick', 'onmousedown', 'onmouseup', 'onmouseover', 'onmousemove', 'onmouseout', 'onkeypress', 'onkeydown', 'onkeyup'),
			'norm' => [],
			'default_html5' => array('contenteditable', 'contextmenu', 'draggable', 'dropzone', 'hidden', 'spellcheck'),
			'html5' => [],
		),
		'label' => array(
			'default' => array('class', 'accesskey', 'tabindex', 'id', 'style', 'title', 'dir', 'lang'),
			'js' => array('onclick', 'ondblclick', 'onmousedown', 'onmouseup', 'onmouseover', 'onmousemove', 'onmouseout', 'onkeypress', 'onkeydown', 'onkeyup', 'onblur', 'onfocus'),
			'norm' => array('accesskey', 'for'),
			'default_html5' => array('contenteditable', 'contextmenu', 'draggable', 'dropzone', 'hidden', 'spellcheck'),
			'html5' => [],
		),
		'legend' => array(
			'default' => array('class', 'accesskey', 'tabindex', 'id', 'style', 'title', 'dir', 'lang'),
			'js' => array('onclick', 'ondblclick', 'onmousedown', 'onmouseup', 'onmouseover', 'onmousemove', 'onmouseout', 'onkeypress', 'onkeydown', 'onkeyup'),
			'norm' => array('accesskey', 'align'),
			'default_html5' => array('contenteditable', 'contextmenu', 'draggable', 'dropzone', 'hidden', 'spellcheck'),
			'html5' => [],
		),
		'li' => array(
			'default' => array('class', 'accesskey', 'tabindex', 'id', 'style', 'title', 'dir', 'lang'),
			'js' => array('onclick', 'ondblclick', 'onmousedown', 'onmouseup', 'onmouseover', 'onmousemove', 'onmouseout', 'onkeypress', 'onkeydown', 'onkeyup'),
			'norm' => array('type', 'value'),
			'default_html5' => array('contenteditable', 'contextmenu', 'draggable', 'dropzone', 'hidden', 'spellcheck'),
			'html5' => [],
		),
		'link' => array(
			'default' => array('class', 'accesskey', 'tabindex', 'id', 'style', 'title', 'dir', 'lang'),
			'js' => array('onclick', 'ondblclick', 'onmousedown', 'onmouseup', 'onmouseover', 'onmousemove', 'onmouseout', 'onkeypress', 'onkeydown', 'onkeyup'),
			'norm' => array('charset', 'href', 'hreflang', 'media', 'rel', 'rev', 'target', 'type'),
			'default_html5' => array('contenteditable', 'contextmenu', 'draggable', 'dropzone', 'hidden', 'spellcheck'),
			'html5' => [],
		),
		'map' => array(
			'default' => array('class', 'accesskey', 'tabindex', 'id', 'style', 'title', 'dir', 'lang'),
			'js' => array('onclick', 'ondblclick', 'onmousedown', 'onmouseup', 'onmouseover', 'onmousemove', 'onmouseout', 'onkeypress', 'onkeydown', 'onkeyup'),
			'norm' => array('name'),
			'default_html5' => array('contenteditable', 'contextmenu', 'draggable', 'dropzone', 'hidden', 'spellcheck'),
			'html5' => [],
		),
		'menu' => array(
			'default' => array('class', 'accesskey', 'tabindex', 'id', 'style', 'title', 'dir', 'lang'),
			'js' => array('onclick', 'ondblclick', 'onmousedown', 'onmouseup', 'onmouseover', 'onmousemove', 'onmouseout', 'onkeypress', 'onkeydown', 'onkeyup'),
			'norm' => array('compact'),
			'default_html5' => array('contenteditable', 'contextmenu', 'draggable', 'dropzone', 'hidden', 'spellcheck'),
			'html5' => [],
		),
		'meta' => array(
			'default' => array('dir', 'lang'),
			'js' => array('onclick', 'ondblclick', 'onmousedown', 'onmouseup', 'onmouseover', 'onmousemove', 'onmouseout', 'onkeypress', 'onkeydown', 'onkeyup'),
			'norm' => array('content', 'http-equiv', 'name', 'scheme'),
			'default_html5' => array('contenteditable', 'contextmenu', 'draggable', 'dropzone', 'hidden', 'spellcheck'),
			'html5' => [],
		),
		'noframes' => array(
			'default' => array('class', 'accesskey', 'tabindex', 'id', 'style', 'title', 'dir', 'lang'),
			'js' => array('onclick', 'ondblclick', 'onmousedown', 'onmouseup', 'onmouseover', 'onmousemove', 'onmouseout', 'onkeypress', 'onkeydown', 'onkeyup'),
			'norm' => [],
			'default_html5' => array('contenteditable', 'contextmenu', 'draggable', 'dropzone', 'hidden', 'spellcheck'),
			'html5' => [],
		),
		'noscript' => array(
			'default' => array('class', 'accesskey', 'tabindex', 'id', 'style', 'title', 'dir', 'lang'),
			'js' => array('onclick', 'ondblclick', 'onmousedown', 'onmouseup', 'onmouseover', 'onmousemove', 'onmouseout', 'onkeypress', 'onkeydown', 'onkeyup'),
			'norm' => [],
			'default_html5' => array('contenteditable', 'contextmenu', 'draggable', 'dropzone', 'hidden', 'spellcheck'),
			'html5' => [],
		),
		'object' => array(
			'default' => array('class', 'accesskey', 'tabindex', 'id', 'style', 'title', 'dir', 'lang'),
			'js' => array('onclick', 'ondblclick', 'onmousedown', 'onmouseup', 'onmouseover', 'onmousemove', 'onmouseout', 'onkeypress', 'onkeydown', 'onkeyup'),
			'norm' => array('align', 'archive', 'border', 'classid', 'codebase', 'codetype', 'data', 'declare', 'height', 'hspace', 'name', 'standby', 'tabindex', 'type', 'usemap', 'vspace', 'width'),
			'default_html5' => array('contenteditable', 'contextmenu', 'draggable', 'dropzone', 'hidden', 'spellcheck'),
			'html5' => [],
		),
		'ol' => array(
			'default' => array('class', 'accesskey', 'tabindex', 'id', 'style', 'title', 'dir', 'lang'),
			'js' => array('onclick', 'ondblclick', 'onmousedown', 'onmouseup', 'onmouseover', 'onmousemove', 'onmouseout', 'onkeypress', 'onkeydown', 'onkeyup'),
			'norm' => array('compact', 'start', 'type'),
			'default_html5' => array('contenteditable', 'contextmenu', 'draggable', 'dropzone', 'hidden', 'spellcheck'),
			'html5' => [],
		),
		'optgroup' => array(
			'default' => array('class', 'accesskey', 'tabindex', 'id', 'style', 'title', 'dir', 'lang'),
			'js' => array('onclick', 'ondblclick', 'onmousedown', 'onmouseup', 'onmouseover', 'onmousemove', 'onmouseout', 'onkeypress', 'onkeydown', 'onkeyup'),
			'norm' => array('disabled="disabled"', 'label'),
			'default_html5' => array('contenteditable', 'contextmenu', 'draggable', 'dropzone', 'hidden', 'spellcheck'),
			'html5' => [],
		),
		'option' => array(
			'default' => array('class', 'accesskey', 'tabindex', 'id', 'style', 'title', 'dir', 'lang'),
			'js' => array('onclick', 'ondblclick', 'onmousedown', 'onmouseup', 'onmouseover', 'onmousemove', 'onmouseout', 'onkeypress', 'onkeydown', 'onkeyup'),
			'norm' => array('disabled="disabled"', 'label', 'selected="selected"', 'value'),
			'default_html5' => array('contenteditable', 'contextmenu', 'draggable', 'dropzone', 'hidden', 'spellcheck'),
			'html5' => [],
		),
		'p' => array(
			'default' => array('class', 'accesskey', 'tabindex', 'id', 'style', 'title', 'dir', 'lang'),
			'js' => array('onclick', 'ondblclick', 'onmousedown', 'onmouseup', 'onmouseover', 'onmousemove', 'onmouseout', 'onkeypress', 'onkeydown', 'onkeyup'),
			'norm' => array('align'),
			'default_html5' => array('contenteditable', 'contextmenu', 'draggable', 'dropzone', 'hidden', 'spellcheck'),
			'html5' => [],
		),
		'param' => array(
			'default' => array('id'),
			'js' => array('onclick', 'ondblclick', 'onmousedown', 'onmouseup', 'onmouseover', 'onmousemove', 'onmouseout', 'onkeypress', 'onkeydown', 'onkeyup'),
			'norm' => array('name', 'type', 'value', 'valuetype'),
			'default_html5' => array('contenteditable', 'contextmenu', 'draggable', 'dropzone', 'hidden', 'spellcheck'),
			'html5' => [],
		),
		'pre' => array(
			'default' => array('class', 'accesskey', 'tabindex', 'id', 'style', 'title', 'dir', 'lang'),
			'js' => array('onclick', 'ondblclick', 'onmousedown', 'onmouseup', 'onmouseover', 'onmousemove', 'onmouseout', 'onkeypress', 'onkeydown', 'onkeyup'),
			'norm' => array('width'),
			'default_html5' => array('contenteditable', 'contextmenu', 'draggable', 'dropzone', 'hidden', 'spellcheck'),
			'html5' => [],
		),
		'q' => array(
			'default' => array('class', 'accesskey', 'tabindex', 'id', 'style', 'title', 'dir', 'lang'),
			'js' => array('onclick', 'ondblclick', 'onmousedown', 'onmouseup', 'onmouseover', 'onmousemove', 'onmouseout', 'onkeypress', 'onkeydown', 'onkeyup'),
			'norm' => array('cite'),
			'default_html5' => array('contenteditable', 'contextmenu', 'draggable', 'dropzone', 'hidden', 'spellcheck'),
			'html5' => [],
		),
		's' => array(
			'default' => array('class', 'accesskey', 'tabindex', 'id', 'style', 'title', 'dir', 'lang'),
			'js' => array('onclick', 'ondblclick', 'onmousedown', 'onmouseup', 'onmouseover', 'onmousemove', 'onmouseout', 'onkeypress', 'onkeydown', 'onkeyup'),
			'norm' => [],
			'default_html5' => array('contenteditable', 'contextmenu', 'draggable', 'dropzone', 'hidden', 'spellcheck'),
			'html5' => [],
		),
		'samp' => array(
			'default' => array('class', 'accesskey', 'tabindex', 'id', 'style', 'title', 'dir', 'lang'),
			'js' => array('onclick', 'ondblclick', 'onmousedown', 'onmouseup', 'onmouseover', 'onmousemove', 'onmouseout', 'onkeypress', 'onkeydown', 'onkeyup'),
			'norm' => [],
			'default_html5' => array('contenteditable', 'contextmenu', 'draggable', 'dropzone', 'hidden', 'spellcheck'),
			'html5' => [],
		),
		'script' => array(
			'default' => [],
			'js' => array('onclick', 'ondblclick', 'onmousedown', 'onmouseup', 'onmouseover', 'onmousemove', 'onmouseout', 'onkeypress', 'onkeydown', 'onkeyup'),
			'norm' => array('charset', 'defer', 'event', 'language', 'for', 'src', 'type'),
			'default_html5' => array('contenteditable', 'contextmenu', 'draggable', 'dropzone', 'hidden', 'spellcheck'),
			'html5' => [],
		),
		'select' => array(
			'default' => array('class', 'accesskey', 'tabindex', 'id', 'style', 'title', 'dir', 'lang'),
			'js' => array('onclick', 'ondblclick', 'onmousedown', 'onmouseup', 'onmouseover', 'onmousemove', 'onmouseout', 'onkeypress', 'onkeydown', 'onkeyup', 'onblur', 'onchange', 'onfocus'),
			'norm' => array('disabled="disabled"', 'multiple', 'name', 'size', 'tabindex'),
			'default_html5' => array('contenteditable', 'contextmenu', 'draggable', 'dropzone', 'hidden', 'spellcheck'),
			'html5' => [],
		),
		'small' => array(
			'default' => array('class', 'accesskey', 'tabindex', 'id', 'style', 'title', 'dir', 'lang'),
			'js' => array('onclick', 'ondblclick', 'onmousedown', 'onmouseup', 'onmouseover', 'onmousemove', 'onmouseout', 'onkeypress', 'onkeydown', 'onkeyup'),
			'norm' => [],
			'default_html5' => array('contenteditable', 'contextmenu', 'draggable', 'dropzone', 'hidden', 'spellcheck'),
			'html5' => [],
		),
		'span' => array(
			'default' => array('class', 'accesskey', 'tabindex', 'id', 'style', 'title', 'dir', 'lang'),
			'js' => array('onclick', 'ondblclick', 'onmousedown', 'onmouseup', 'onmouseover', 'onmousemove', 'onmouseout', 'onkeypress', 'onkeydown', 'onkeyup'),
			'norm' => [],
			'default_html5' => array('contenteditable', 'contextmenu', 'draggable', 'dropzone', 'hidden', 'spellcheck'),
			'html5' => [],
		),
		'strike' => array(
			'default' => array('class', 'accesskey', 'tabindex', 'id', 'style', 'title', 'dir', 'lang'),
			'js' => array('onclick', 'ondblclick', 'onmousedown', 'onmouseup', 'onmouseover', 'onmousemove', 'onmouseout', 'onkeypress', 'onkeydown', 'onkeyup'),
			'norm' => [],
			'default_html5' => array('contenteditable', 'contextmenu', 'draggable', 'dropzone', 'hidden', 'spellcheck'),
			'html5' => [],
		),
		'strong' => array(
			'default' => array('class', 'accesskey', 'tabindex', 'id', 'style', 'title', 'dir', 'lang'),
			'js' => array('onclick', 'ondblclick', 'onmousedown', 'onmouseup', 'onmouseover', 'onmousemove', 'onmouseout', 'onkeypress', 'onkeydown', 'onkeyup'),
			'norm' => [],
			'default_html5' => array('contenteditable', 'contextmenu', 'draggable', 'dropzone', 'hidden', 'spellcheck'),
			'html5' => [],
		),
		'style' => array(
			'default' => array('title', 'dir', 'lang'),
			'js' => [],
			'norm' => array('media', 'type'),
			'default_html5' => array('contenteditable', 'contextmenu', 'draggable', 'dropzone', 'hidden', 'spellcheck'),
			'html5' => [],
		),
		'sub' => array(
			'default' => array('class', 'accesskey', 'tabindex', 'id', 'style', 'title', 'dir', 'lang'),
			'js' => array('onclick', 'ondblclick', 'onmousedown', 'onmouseup', 'onmouseover', 'onmousemove', 'onmouseout', 'onkeypress', 'onkeydown', 'onkeyup'),
			'norm' => [],
			'default_html5' => array('contenteditable', 'contextmenu', 'draggable', 'dropzone', 'hidden', 'spellcheck'),
			'html5' => [],
		),
		'sup' => array(
			'default' => array('class', 'accesskey', 'tabindex', 'id', 'style', 'title', 'dir', 'lang'),
			'js' => array('onclick', 'ondblclick', 'onmousedown', 'onmouseup', 'onmouseover', 'onmousemove', 'onmouseout', 'onkeypress', 'onkeydown', 'onkeyup'),
			'norm' => [],
			'default_html5' => array('contenteditable', 'contextmenu', 'draggable', 'dropzone', 'hidden', 'spellcheck'),
			'html5' => [],
		),
		'table' => array(
			'default' => array('class', 'accesskey', 'tabindex', 'id', 'style', 'title', 'dir', 'lang'),
			'js' => array('onclick', 'ondblclick', 'onmousedown', 'onmouseup', 'onmouseover', 'onmousemove', 'onmouseout', 'onkeypress', 'onkeydown', 'onkeyup'),
			'norm' => array('align', 'background', 'bgcolor', 'border', 'cellpadding', 'cellspacing', 'frame', 'rules', 'summary', 'width'),
			'default_html5' => array('contenteditable', 'contextmenu', 'draggable', 'dropzone', 'hidden', 'spellcheck'),
			'html5' => [],
		),
		'tbody' => array(
			'default' => array('class', 'accesskey', 'tabindex', 'id', 'style', 'title', 'dir', 'lang'),
			'js' => array('onclick', 'ondblclick', 'onmousedown', 'onmouseup', 'onmouseover', 'onmousemove', 'onmouseout', 'onkeypress', 'onkeydown', 'onkeyup'),
			'norm' => array('align', 'char', 'charoff', 'valign'),
			'default_html5' => array('contenteditable', 'contextmenu', 'draggable', 'dropzone', 'hidden', 'spellcheck'),
			'html5' => [],
		),
		'td' => array(
			'default' => array('class', 'accesskey', 'tabindex', 'id', 'style', 'title', 'dir', 'lang'),
			'js' => array('onclick', 'ondblclick', 'onmousedown', 'onmouseup', 'onmouseover', 'onmousemove', 'onmouseout', 'onkeypress', 'onkeydown', 'onkeyup'),
			'norm' => array('abbr', 'align', 'axis', 'background', 'bgcolor', 'char', 'charoff', 'colspan', 'headers', 'height', 'nowrap', 'rowspan', 'scope', 'valign', 'width'),
			'default_html5' => array('contenteditable', 'contextmenu', 'draggable', 'dropzone', 'hidden', 'spellcheck'),
			'html5' => [],
		),
		'textarea' => array(
			'default' => array('class', 'accesskey', 'tabindex', 'id', 'style', 'title', 'dir', 'lang'),
			'js' => array('onclick', 'ondblclick', 'onmousedown', 'onmouseup', 'onmouseover', 'onmousemove', 'onmouseout', 'onkeypress', 'onkeydown', 'onkeyup', 'onblur', 'onchange', 'onfocus', 'onselect'),
			'norm' => array('accesskey', 'cols', 'disabled="disabled"', 'name', 'readonly', 'rows', 'tabindex'),
			'default_html5' => array('contenteditable', 'contextmenu', 'draggable', 'dropzone', 'hidden', 'spellcheck'),
			'html5' => [],
		),
		'tfoot' => array(
			'default' => array('class', 'accesskey', 'tabindex', 'id', 'style', 'title', 'dir', 'lang'),
			'js' => array('onclick', 'ondblclick', 'onmousedown', 'onmouseup', 'onmouseover', 'onmousemove', 'onmouseout', 'onkeypress', 'onkeydown', 'onkeyup'),
			'norm' => array('align', 'char', 'charoff', 'valign'),
			'default_html5' => array('contenteditable', 'contextmenu', 'draggable', 'dropzone', 'hidden', 'spellcheck'),
			'html5' => [],
		),
		'th' => array(
			'default' => array('class', 'accesskey', 'tabindex', 'id', 'style', 'title', 'dir', 'lang'),
			'js' => array('onclick', 'ondblclick', 'onmousedown', 'onmouseup', 'onmouseover', 'onmousemove', 'onmouseout', 'onkeypress', 'onkeydown', 'onkeyup'),
			'norm' => array('align', 'axis', 'background', 'bgcolor', 'char', 'charoff', 'colspan', 'headers', 'height', 'nowrap', 'rowspan', 'scope', 'valign', 'width'),
			'default_html5' => array('contenteditable', 'contextmenu', 'draggable', 'dropzone', 'hidden', 'spellcheck'),
			'html5' => [],
		),
		'thead' => array(
			'default' => array('class', 'accesskey', 'tabindex', 'id', 'style', 'title', 'dir', 'lang'),
			'js' => array('onclick', 'ondblclick', 'onmousedown', 'onmouseup', 'onmouseover', 'onmousemove', 'onmouseout', 'onkeypress', 'onkeydown', 'onkeyup'),
			'norm' => array('align', 'char', 'charoff', 'valign'),
			'default_html5' => array('contenteditable', 'contextmenu', 'draggable', 'dropzone', 'hidden', 'spellcheck'),
			'html5' => [],
		),
		'title' => array(
			'default' => array('dir', 'lang'),
			'js' => [],
			'norm' => [],
			'default_html5' => array('contenteditable', 'contextmenu', 'draggable', 'dropzone', 'hidden', 'spellcheck'),
			'html5' => [],
		),
		'tr' => array(
			'default' => array('class', 'accesskey', 'tabindex', 'id', 'style', 'title', 'dir', 'lang'),
			'js' => array('onclick', 'ondblclick', 'onmousedown', 'onmouseup', 'onmouseover', 'onmousemove', 'onmouseout', 'onkeypress', 'onkeydown', 'onkeyup'),
			'norm' => array('align', 'background', 'bgcolor', 'char', 'charoff', 'valign'),
			'default_html5' => array('contenteditable', 'contextmenu', 'draggable', 'dropzone', 'hidden', 'spellcheck'),
			'html5' => [],
		),
		'tt' => array(
			'default' => array('class', 'accesskey', 'tabindex', 'id', 'style', 'title', 'dir', 'lang'),
			'js' => array('onclick', 'ondblclick', 'onmousedown', 'onmouseup', 'onmouseover', 'onmousemove', 'onmouseout', 'onkeypress', 'onkeydown', 'onkeyup'),
			'norm' => [],
			'default_html5' => array('contenteditable', 'contextmenu', 'draggable', 'dropzone', 'hidden', 'spellcheck'),
			'html5' => [],
		),
		'u' => array(
			'default' => array('class', 'accesskey', 'tabindex', 'id', 'style', 'title', 'dir', 'lang'),
			'js' => array('onclick', 'ondblclick', 'onmousedown', 'onmouseup', 'onmouseover', 'onmousemove', 'onmouseout', 'onkeypress', 'onkeydown', 'onkeyup'),
			'norm' => [],
			'default_html5' => array('contenteditable', 'contextmenu', 'draggable', 'dropzone', 'hidden', 'spellcheck'),
			'html5' => [],
		),
		'ul' => array(
			'default' => array('class', 'accesskey', 'tabindex', 'id', 'style', 'title', 'dir', 'lang'),
			'js' => array('onclick', 'ondblclick', 'onmousedown', 'onmouseup', 'onmouseover', 'onmousemove', 'onmouseout', 'onkeypress', 'onkeydown', 'onkeyup'),
			'norm' => array('compact', 'type'),
			'default_html5' => array('contenteditable', 'contextmenu', 'draggable', 'dropzone', 'hidden', 'spellcheck'),
			'html5' => [],
		),
		'var' => array(
			'default' => array('class', 'accesskey', 'tabindex', 'id', 'style', 'title', 'dir', 'lang'),
			'js' => array('onclick', 'ondblclick', 'onmousedown', 'onmouseup', 'onmouseover', 'onmousemove', 'onmouseout', 'onkeypress', 'onkeydown', 'onkeyup'),
			'norm' => [],
			'default_html5' => array('contenteditable', 'contextmenu', 'draggable', 'dropzone', 'hidden', 'spellcheck'),
			'html5' => [],
		),
		'!DOCTYPE' => array(
		),
		'?php' => array(
		),
	),
	'html5' => ['article' => array(
			'default' => array('class', 'accesskey', 'tabindex', 'id', 'style', 'title', 'dir', 'lang'),
			'js' => array('onclick', 'ondblclick', 'onmousedown', 'onmouseup', 'onmouseover', 'onmousemove', 'onmouseout', 'onkeypress', 'onkeydown', 'onkeyup'),
			'norm' => [],
			'default_html5' => array('contenteditable', 'contextmenu', 'draggable', 'dropzone', 'hidden', 'spellcheck'),
			'html5' => [],
		),
		'aside' => array(
			'default' => array('class', 'accesskey', 'tabindex', 'id', 'style', 'title', 'dir', 'lang'),
			'js' => array('onclick', 'ondblclick', 'onmousedown', 'onmouseup', 'onmouseover', 'onmousemove', 'onmouseout', 'onkeypress', 'onkeydown', 'onkeyup'),
			'norm' => [],
			'default_html5' => array('contenteditable', 'contextmenu', 'draggable', 'dropzone', 'hidden', 'spellcheck'),
			'html5' => [],
		),
		'bdi' => array(
			'default' => array('class', 'accesskey', 'tabindex', 'id', 'style', 'title', 'dir', 'lang'),
			'js' => array('onclick', 'ondblclick', 'onmousedown', 'onmouseup', 'onmouseover', 'onmousemove', 'onmouseout', 'onkeypress', 'onkeydown', 'onkeyup'),
			'norm' => [],
			'default_html5' => array('contenteditable', 'contextmenu', 'draggable', 'dropzone', 'hidden', 'spellcheck'),
			'html5' => [],
		),
		'command' => array(
			'default' => array('class', 'accesskey', 'tabindex', 'id', 'style', 'title', 'dir', 'lang'),
			'js' => array('onclick', 'ondblclick', 'onmousedown', 'onmouseup', 'onmouseover', 'onmousemove', 'onmouseout', 'onkeypress', 'onkeydown', 'onkeyup'),
			'norm' => [],
			'default_html5' => array('contenteditable', 'contextmenu', 'draggable', 'dropzone', 'hidden', 'spellcheck'),
			'html5' => [],
		),
		'details' => array(
			'default' => array('class', 'accesskey', 'tabindex', 'id', 'style', 'title', 'dir', 'lang'),
			'js' => array('onclick', 'ondblclick', 'onmousedown', 'onmouseup', 'onmouseover', 'onmousemove', 'onmouseout', 'onkeypress', 'onkeydown', 'onkeyup'),
			'norm' => [],
			'default_html5' => array('contenteditable', 'contextmenu', 'draggable', 'dropzone', 'hidden', 'spellcheck'),
			'html5' => [],
		),
		'summary' => array(
			'default' => array('class', 'accesskey', 'tabindex', 'id', 'style', 'title', 'dir', 'lang'),
			'js' => array('onclick', 'ondblclick', 'onmousedown', 'onmouseup', 'onmouseover', 'onmousemove', 'onmouseout', 'onkeypress', 'onkeydown', 'onkeyup'),
			'norm' => [],
			'default_html5' => array('contenteditable', 'contextmenu', 'draggable', 'dropzone', 'hidden', 'spellcheck'),
			'html5' => [],
		),
		'figure' => array(
			'default' => array('class', 'accesskey', 'tabindex', 'id', 'style', 'title', 'dir', 'lang'),
			'js' => array('onclick', 'ondblclick', 'onmousedown', 'onmouseup', 'onmouseover', 'onmousemove', 'onmouseout', 'onkeypress', 'onkeydown', 'onkeyup'),
			'norm' => [],
			'default_html5' => array('contenteditable', 'contextmenu', 'draggable', 'dropzone', 'hidden', 'spellcheck'),
			'html5' => [],
		),
		'figcaption' => array(
			'default' => array('class', 'accesskey', 'tabindex', 'id', 'style', 'title', 'dir', 'lang'),
			'js' => array('onclick', 'ondblclick', 'onmousedown', 'onmouseup', 'onmouseover', 'onmousemove', 'onmouseout', 'onkeypress', 'onkeydown', 'onkeyup'),
			'norm' => [],
			'default_html5' => array('contenteditable', 'contextmenu', 'draggable', 'dropzone', 'hidden', 'spellcheck'),
			'html5' => [],
		),
		'footer' => array(
			'default' => array('class', 'accesskey', 'tabindex', 'id', 'style', 'title', 'dir', 'lang'),
			'js' => array('onclick', 'ondblclick', 'onmousedown', 'onmouseup', 'onmouseover', 'onmousemove', 'onmouseout', 'onkeypress', 'onkeydown', 'onkeyup'),
			'norm' => [],
			'default_html5' => array('contenteditable', 'contextmenu', 'draggable', 'dropzone', 'hidden', 'spellcheck'),
			'html5' => [],
		),
		'header' => array(
			'default' => array('class', 'accesskey', 'tabindex', 'id', 'style', 'title', 'dir', 'lang'),
			'js' => array('onclick', 'ondblclick', 'onmousedown', 'onmouseup', 'onmouseover', 'onmousemove', 'onmouseout', 'onkeypress', 'onkeydown', 'onkeyup'),
			'norm' => [],
			'default_html5' => array('contenteditable', 'contextmenu', 'draggable', 'dropzone', 'hidden', 'spellcheck'),
			'html5' => [],
		),
		'hgroup' => array(
			'default' => array('class', 'accesskey', 'tabindex', 'id', 'style', 'title', 'dir', 'lang'),
			'js' => array('onclick', 'ondblclick', 'onmousedown', 'onmouseup', 'onmouseover', 'onmousemove', 'onmouseout', 'onkeypress', 'onkeydown', 'onkeyup'),
			'norm' => [],
			'default_html5' => array('contenteditable', 'contextmenu', 'draggable', 'dropzone', 'hidden', 'spellcheck'),
			'html5' => [],
		),
		'mark' => array(
			'default' => array('class', 'accesskey', 'tabindex', 'id', 'style', 'title', 'dir', 'lang'),
			'js' => array('onclick', 'ondblclick', 'onmousedown', 'onmouseup', 'onmouseover', 'onmousemove', 'onmouseout', 'onkeypress', 'onkeydown', 'onkeyup'),
			'norm' => [],
			'default_html5' => array('contenteditable', 'contextmenu', 'draggable', 'dropzone', 'hidden', 'spellcheck'),
			'html5' => [],
		),
		'meter' => array(
			'default' => array('class', 'accesskey', 'tabindex', 'id', 'style', 'title', 'dir', 'lang'),
			'js' => array('onclick', 'ondblclick', 'onmousedown', 'onmouseup', 'onmouseover', 'onmousemove', 'onmouseout', 'onkeypress', 'onkeydown', 'onkeyup'),
			'norm' => [],
			'default_html5' => array('contenteditable', 'contextmenu', 'draggable', 'dropzone', 'hidden', 'spellcheck'),
			'html5' => [],
		),
		'nav' => array(
			'default' => array('class', 'accesskey', 'tabindex', 'id', 'style', 'title', 'dir', 'lang'),
			'js' => array('onclick', 'ondblclick', 'onmousedown', 'onmouseup', 'onmouseover', 'onmousemove', 'onmouseout', 'onkeypress', 'onkeydown', 'onkeyup'),
			'norm' => [],
			'default_html5' => array('contenteditable', 'contextmenu', 'draggable', 'dropzone', 'hidden', 'spellcheck'),
			'html5' => [],
		),
		'progress' => array(
			'default' => array('class', 'accesskey', 'tabindex', 'id', 'style', 'title', 'dir', 'lang'),
			'js' => array('onclick', 'ondblclick', 'onmousedown', 'onmouseup', 'onmouseover', 'onmousemove', 'onmouseout', 'onkeypress', 'onkeydown', 'onkeyup'),
			'norm' => [],
			'default_html5' => array('contenteditable', 'contextmenu', 'draggable', 'dropzone', 'hidden', 'spellcheck'),
			'html5' => [],
		),
		'ruby' => array(
			'default' => array('class', 'accesskey', 'tabindex', 'id', 'style', 'title', 'dir', 'lang'),
			'js' => array('onclick', 'ondblclick', 'onmousedown', 'onmouseup', 'onmouseover', 'onmousemove', 'onmouseout', 'onkeypress', 'onkeydown', 'onkeyup'),
			'norm' => [],
			'default_html5' => array('contenteditable', 'contextmenu', 'draggable', 'dropzone', 'hidden', 'spellcheck'),
			'html5' => [],
		),
		'rt' => array(
			'default' => array('class', 'accesskey', 'tabindex', 'id', 'style', 'title', 'dir', 'lang'),
			'js' => array('onclick', 'ondblclick', 'onmousedown', 'onmouseup', 'onmouseover', 'onmousemove', 'onmouseout', 'onkeypress', 'onkeydown', 'onkeyup'),
			'norm' => [],
			'default_html5' => array('contenteditable', 'contextmenu', 'draggable', 'dropzone', 'hidden', 'spellcheck'),
			'html5' => [],
		),
		'rp' => array(
			'default' => array('class', 'accesskey', 'tabindex', 'id', 'style', 'title', 'dir', 'lang'),
			'js' => array('onclick', 'ondblclick', 'onmousedown', 'onmouseup', 'onmouseover', 'onmousemove', 'onmouseout', 'onkeypress', 'onkeydown', 'onkeyup'),
			'norm' => [],
			'default_html5' => array('contenteditable', 'contextmenu', 'draggable', 'dropzone', 'hidden', 'spellcheck'),
			'html5' => [],
		),
		'section' => array(
			'default' => array('class', 'accesskey', 'tabindex', 'id', 'style', 'title', 'dir', 'lang'),
			'js' => array('onclick', 'ondblclick', 'onmousedown', 'onmouseup', 'onmouseover', 'onmousemove', 'onmouseout', 'onkeypress', 'onkeydown', 'onkeyup'),
			'norm' => [],
			'default_html5' => array('contenteditable', 'contextmenu', 'draggable', 'dropzone', 'hidden', 'spellcheck'),
			'html5' => [],
		),
		'time' => array(
			'default' => array('class', 'accesskey', 'tabindex', 'id', 'style', 'title', 'dir', 'lang'),
			'js' => array('onclick', 'ondblclick', 'onmousedown', 'onmouseup', 'onmouseover', 'onmousemove', 'onmouseout', 'onkeypress', 'onkeydown', 'onkeyup'),
			'norm' => [],
			'default_html5' => array('contenteditable', 'contextmenu', 'draggable', 'dropzone', 'hidden', 'spellcheck'),
			'html5' => [],
		),
		'wbr' => array(
			'default' => array('class', 'accesskey', 'tabindex', 'id', 'style', 'title', 'dir', 'lang'),
			'js' => array('onclick', 'ondblclick', 'onmousedown', 'onmouseup', 'onmouseover', 'onmousemove', 'onmouseout', 'onkeypress', 'onkeydown', 'onkeyup'),
			'norm' => [],
			'default_html5' => array('contenteditable', 'contextmenu', 'draggable', 'dropzone', 'hidden', 'spellcheck'),
			'html5' => [],
		),
		'audio' => array(
			'default' => array('class', 'accesskey', 'tabindex', 'id', 'style', 'title', 'dir', 'lang'),
			'js' => array('onclick', 'ondblclick', 'onmousedown', 'onmouseup', 'onmouseover', 'onmousemove', 'onmouseout', 'onkeypress', 'onkeydown', 'onkeyup'),
			'norm' => [],
			'default_html5' => array('contenteditable', 'contextmenu', 'draggable', 'dropzone', 'hidden', 'spellcheck'),
			'html5' => [],
		),
		'video' => array(
			'default' => array('class', 'accesskey', 'tabindex', 'id', 'style', 'title', 'dir', 'lang'),
			'js' => array('onclick', 'ondblclick', 'onmousedown', 'onmouseup', 'onmouseover', 'onmousemove', 'onmouseout', 'onkeypress', 'onkeydown', 'onkeyup'),
			'norm' => [],
			'default_html5' => array('contenteditable', 'contextmenu', 'draggable', 'dropzone', 'hidden', 'spellcheck'),
			'html5' => [],
		),
		'source' => array(
			'default' => array('class', 'accesskey', 'tabindex', 'id', 'style', 'title', 'dir', 'lang'),
			'js' => array('onclick', 'ondblclick', 'onmousedown', 'onmouseup', 'onmouseover', 'onmousemove', 'onmouseout', 'onkeypress', 'onkeydown', 'onkeyup'),
			'norm' => [],
			'default_html5' => ['contenteditable', 'contextmenu', 'draggable', 'dropzone', 'hidden', 'spellcheck'],
			'html5' => [],
		),
		'embed' => [
			'default' => ['class', 'accesskey', 'tabindex', 'id', 'style', 'title', 'dir', 'lang'],
			'js' => ['onclick', 'ondblclick', 'onmousedown', 'onmouseup', 'onmouseover', 'onmousemove', 'onmouseout', 'onkeypress', 'onkeydown', 'onkeyup'],
			'norm' => [],
			'default_html5' => ['contenteditable', 'contextmenu', 'draggable', 'dropzone', 'hidden', 'spellcheck'],
			'html5' => [],
		],
		'track' => [
			'default' => ['class', 'accesskey', 'tabindex', 'id', 'style', 'title', 'dir', 'lang'],
			'js' => ['onclick', 'ondblclick', 'onmousedown', 'onmouseup', 'onmouseover', 'onmousemove', 'onmouseout', 'onkeypress', 'onkeydown', 'onkeyup'],
			'norm' => [],
			'default_html5' => ['contenteditable', 'contextmenu', 'draggable', 'dropzone', 'hidden', 'spellcheck'],
			'html5' => [],
		],
		'canvas' => [
			'default' => ['class', 'accesskey', 'tabindex', 'id', 'style', 'title', 'dir', 'lang'],
			'js' => ['onclick', 'ondblclick', 'onmousedown', 'onmouseup', 'onmouseover', 'onmousemove', 'onmouseout', 'onkeypress', 'onkeydown', 'onkeyup'],
			'norm' => [],
			'default_html5' => ['contenteditable', 'contextmenu', 'draggable', 'dropzone', 'hidden', 'spellcheck'],
			'html5' => [],
		],
		'datalist' => [
			'default' => ['class', 'accesskey', 'tabindex', 'id', 'style', 'title', 'dir', 'lang'],
			'js' => ['onclick', 'ondblclick', 'onmousedown', 'onmouseup', 'onmouseover', 'onmousemove', 'onmouseout', 'onkeypress', 'onkeydown', 'onkeyup'],
			'norm' => [],
			'default_html5' => ['contenteditable', 'contextmenu', 'draggable', 'dropzone', 'hidden', 'spellcheck'],
			'html5' => [],
		],
		'keygen' => [
			'default' => ['class', 'accesskey', 'tabindex', 'id', 'style', 'title', 'dir', 'lang'],
			'js' => ['onclick', 'ondblclick', 'onmousedown', 'onmouseup', 'onmouseover', 'onmousemove', 'onmouseout', 'onkeypress', 'onkeydown', 'onkeyup'],
			'norm' => [],
			'default_html5' => ['contenteditable', 'contextmenu', 'draggable', 'dropzone', 'hidden', 'spellcheck'],
			'html5' => [],
		],
		'output' => [
			'default' => ['class', 'accesskey', 'tabindex', 'id', 'style', 'title', 'dir', 'lang'],
			'js' => ['onclick', 'ondblclick', 'onmousedown', 'onmouseup', 'onmouseover', 'onmousemove', 'onmouseout', 'onkeypress', 'onkeydown', 'onkeyup'],
			'norm' => [],
			'default_html5' => ['contenteditable', 'contextmenu', 'draggable', 'dropzone', 'hidden', 'spellcheck'],
			'html5' => [],
		],
	]
];
